
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team03-s24-4pm-1
owner: ucsb-cs156-s24
repo_name: team03-s24-4pm-1
pull_requests: [{"author":{"id":"U_kgDOBX3XhQ","is_bot":false,"login":"phamaiden","name":""},"headRefName":"Aiden-HelpRequest-Fixtures","number":70,"title":"HelpRequest Fixtures","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-1/pull/70"},{"author":{"id":"U_kgDOB7yP8g","is_bot":false,"login":"RuizheJiang","name":""},"headRefName":"Ruizhe-MenuItem","number":69,"title":"Ruizhe -  upload backend menuitem files","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-1/pull/69"},{"author":{"id":"U_kgDOBX3XhQ","is_bot":false,"login":"phamaiden","name":""},"headRefName":"Aiden-HelpRequest","number":68,"title":"copied code from team02","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-1/pull/68"},{"author":{"id":"MDQ6VXNlcjkwOTg2OTAy","is_bot":false,"login":"miguel-luis9","name":""},"headRefName":"Luis-Articles","number":66,"title":"create personal dokku dev","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-1/pull/66"}]
