
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team03-s24-4pm-1
owner: ucsb-cs156-s24
repo_name: team03-s24-4pm-1
pull_requests: [{"author":{"id":"MDQ6VXNlcjkwOTg2OTAy","is_bot":false,"login":"miguel-luis9","name":""},"headRefName":"LM-Articles-tests","number":92,"title":"Lm articles tests","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-1/pull/92"},{"author":{"id":"MDQ6VXNlcjkwOTg2OTAy","is_bot":false,"login":"miguel-luis9","name":""},"headRefName":"LM-Articles-all","number":90,"title":"Lm articles all - pushed changes for all Articles issues","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-1/pull/90"}]
