
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team03-s24-4pm-1
owner: ucsb-cs156-s24
repo_name: team03-s24-4pm-1
pull_requests: [{"author":{"id":"MDQ6VXNlcjkwOTg2OTAy","is_bot":false,"login":"miguel-luis9","name":""},"headRefName":"LM-Articles-all","number":90,"title":"Lm articles all - pushed changes for all Articles issues","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-1/pull/90"},{"author":{"id":"U_kgDOBqpQ0A","is_bot":false,"login":"monicatrinh1","name":"Monica Trinh"},"headRefName":"Monica-RecRequest-Table","number":88,"title":"MT- Form and Table Component for RecommendationRequest plus tests","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-1/pull/88"},{"author":{"id":"U_kgDOBXjsvQ","is_bot":false,"login":"ericknee","name":""},"headRefName":"Eric-MenuItemReview","number":84,"title":"EN - Adjusted MenuItemReview Form and tests for full mutation coverage","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-1/pull/84"},{"author":{"id":"U_kgDOBmDgZA","is_bot":false,"login":"Frank404NotFound","name":"Frank Zhong"},"headRefName":"fz-orgsNavbar","number":83,"title":"Fz orgs navbar","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-1/pull/83"}]
